### ISSUE TITLE
Time-dependent exposure missing from vignettes

### ISSUE THREAD

**Issue by wiedenhoeft** [sahirbhatnagar/casebase#160] opened 2023-07-27 09:05 UTC
I am interested in using casebase for time-dependent variables (not time-dependent influence of a constant variable on the hazard), specifically in the context of competing risks. At https://journal.r-project.org/articles/RJ-2022-052/, the following is mentioned: 

> In one of the package vignettes, we use the Stanford Heart Transplant data Crowley and Hu ([1977] to show how case-base sampling can also be used in the context of time-dependent exposure.

However, I was not able to find this in any of the package vignettes on CRAN. Any pointers or examples of how to use time-dependent predictors would be greatly appreciated :-)

**Comment by turgeonmaxime** [comment] 2023-07-27 13:47
Thanks for your interest in casebase! You're right, that vignette doesn't exist (yet!). the Stanford Heart Transplant case-study was part of an earlier draft of the paper, but we removed it with the intention of putting the code in a vignette. I'll track down the code and put it in a vignette as intended, and I'll let you know once it's available (probably in the next few days).

**Comment by turgeonmaxime** [comment] 2023-08-03 02:14
Hi @wiedenhoeft, I see that you've received some excellent advice by email from Olli! As promised, I added the vignette that we mentioned in the paper. Until we update the website, you can find a pdf version here: https://github.com/sahirbhatnagar/casebase/blob/master/vignettes/time-varying-covariates.pdf

I'll close this issue, but feel free to ask any further question.

**Closed by turgeonmaxime** 2023-08-03 02:14 UTC
